# Generated by Django 4.2.6 on 2023-12-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
